orgs = [
    "Allen Institute for AI",
    "Stanford",
    "UC Berkeley",
    "University of California",
    "MIT",
    "Massachusetts Institute of Technology",
    "CMU",
    "Carnegie Mellon",
    "Princeton University",
    "Washington University",
    "UIUC",
    "University of Illinois Urbana-Champaign",
    "Georgia Institute of Technology",
    "New York University",
    "California Institute of Technology",
    "UT Austin",
    "University of Texas at Austin",
    "University of Maryland, College Park",
    "University of Michigan",
    "Cornell University",
    "Columbia University",
    "Harvard University",
    "University of Toronto",
    "University of Waterloo",
    "Université du Québec à Montréal",
    "McGill University",
    "AI2",
    "Mila",
    "Quebec Artificial Intelligence Institute",
    "Vector Institute",
    "Amii",
    "Alberta Machine Intelligence Institute",
    "University of British Columbia",
    "UBC",
    "Apple",
    "NVIDIA",
    "Xai",
    "Cohere",
    "Databricks",
    "Scale AI",
    "Together AI",
    "Figure AI",
    "Intel",
    "IBM",
    "Amazon",
    "AWS",
    "Physical AI",
    "Tesla",
    "Adobe",
    "Meta",
    "Mistral",
    "Microsoft",
    "Anthropic",
    "Alibaba",
    "DeepSeek",
    "ByteDance",
    "OpenAI",
    "Google",
    "DeepMind",
    "Oxford"
]